### ISSUE TITLE
Final Summary Page (image generation) QA - Several issues

### ISSUE THREAD

**Issue by laurenluz** [CommonsBuild/commons-config-frontend#165]
## Token Freeze / Token Thaw

- [x] It's weird that #of weeks is in intervals of 13 weeks. Would be better if it was 12 weeks or **3 month** intervals.
- [x] should say % **OF** TOKENS RELEASED

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/77e2bc01-6161-48bf-9f47-91dfb1625403)

## ABC

- [x] Is there some way we can indicate that the step being shown is Step 0 / initial buy?
- [x] Units on the x-axis should really say "x1000 wxDai", or we should indicate this "x1000" somewhere else #164

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/4307433a-461e-4b8f-8e43-b1c828b4b8ea)

## Tao Voting

- [x]  We're missing the legend here that explains what each of the colours mean

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/cb88e897-a05d-42de-8256-f5043bdb7764)

- [x] These tooltips are not producing a hover yet. They need content. Or perhaps can be removed? Just keep the one on "
"Quiet Ending Extensions" for sure 
- [x] Can this table be modified so that the first *column* is bolded and the rest are not? 
- [x] add "(DAYS)" to end of "TOTAL AMOUNT OF TIME TO COMPLETE A VOTE"

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/4984561b-97c7-4cfc-b9e4-86e3c299a9ce)

## Conviction Voting

- [x] Hover on "effective supply" should be closer to the graph, it's really far away right now.
- [x] should we move this "min % of tokens needed to pass" box onto the graph... closer to the line? it's hard to understand what this is pointing to right now.
- [x] "COMMON POOL" on x-axis should be yellow because it is a hover

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/cc31cc52-14eb-48c1-b95f-80728b6e2751)

**Comment by GriffGreen** [comment]
Add this to the top corner
![Screen Shot 2021-11-07 at 12 47 05 PM](https://user-images.githubusercontent.com/14945613/140657802-f45e7c44-e5e0-40bc-86c0-accfd9ae9567.png)
 of the graph like Reserve ratio?

**Comment by GriffGreen** [comment]
Move Box to top right

**Comment by divine-comedian** [comment]
text updated in config/4 header 

https://github.com/CommonsBuild/commons-config-frontend/commit/42ca4809cfc7767a1f07871f2a6a18536a6a1f5f

**Comment by GriffGreen** [comment]
@divine-comedian I think its too long 
<img width="737" alt="Screen Shot 2021-11-10 at 11 14 29 PM" src="https://user-images.githubusercontent.com/14945613/141241799-c5922e62-bf47-4c55-b8da-8f627f4393d4.png">


What if we changed it from: 

Visualize how Conviction works and the requirements for successfully requesting funds. Use the graph below to see the minimum percent of tokens needed to pass funding requests.

to 

Visualize the percent of tokens needed to pass funding requests in Conviction Voting.

Also we could try to tighten up the ABC's as well:

Experience your Augmented Bonding Curve by adjusting your parameters and experimenting with the Step Simulator.

to 

Experience your Augmented Bonding Curve by adjusting your params and adding steps.

**Comment by divine-comedian** [comment]
> @divine-comedian I think its too long <img alt="Screen Shot 2021-11-10 at 11 14 29 PM" width="737" src="https://user-images.githubusercontent.com/14945613/141241799-c5922e62-bf47-4c55-b8da-8f627f4393d4.png">
> 
> What if we changed it from:
> 
> Visualize how Conviction works and the requirements for successfully requesting funds. Use the graph below to see the minimum percent of tokens needed to pass funding requests.
> 
> to
> 
> Visualize the percent of tokens needed to pass funding requests in Conviction Voting.
> 
> Also we could try to tighten up the ABC's as well:
> 
> Experience your Augmented Bonding Curve by adjusting your parameters and experimenting with the Step Simulator.
> 
> to
> 
> Experience your Augmented Bonding Curve by adjusting your params and adding steps.

Params is cool but its not actually a real word and might not be obvious for non-english native speakers
