### ISSUE TITLE
Add to the Commons Tribute tool tip

### ISSUE THREAD

**Issue by GriffGreen** [CommonsBuild/commons-config-frontend#167]
![Screen Shot 2021-11-03 at 4 48 15 PM](https://user-images.githubusercontent.com/14945613/140223489-4d3656e0-c781-41f4-a53a-b423fca9eb54.png)

"A" should be "The"

And From Gideon:

Its not clear that the Commons Tribute impacts the Reserve! Add something to the tool tip to make that clear. (IMO this should be added)

Also

It needs to be more clear that the Commons Tribute is a one time thing and the entry/exit tributes are continuous (This one I'm more open to not changing... it might be complex to communicate.)

**Comment by divine-comedian** [comment]
Okay, I incorporated your suggestions - 

`      <span>This is a percentage of the total funds raised from the Hatch, and is sent to the Common Pool to kick-start the Commons project.<b>The remaining percentage determines the Reserve Balance.</b></span>`

**Comment by divine-comedian** [comment]
committed to develop - https://github.com/CommonsBuild/commons-config-frontend/commit/a7c43ed7285f6fb7fedb9934f918b2383b608661
