### ISSUE TITLE
"Support required" is allowing values below 50%

### ISSUE THREAD

**Issue by PabloCGL** [CommonsBuild/commons-config-frontend#172]
This has caused some confusion, since people have thought that the percentage applied to the total of the possible voting power and not to the votes on the actual vote... maybe also the tooltip could be more specific @divine-comedian ? I have a hard time thinking how, but maybe you can work your magic :grin:

**Comment by divine-comedian** [comment]
text modified on develop in commit - https://github.com/CommonsBuild/commons-config-frontend/commit/a7c43ed7285f6fb7fedb9934f918b2383b608661
