### ISSUE TITLE
Require Support Required always be above 50%

### ISSUE THREAD

**Issue by GriffGreen** [CommonsBuild/commons-config-frontend#175]
Someone actually sent a 42% support required... that doesnt make sense!

<img width="256" alt="Screen Shot 2021-11-05 at 1 52 12 PM" src="https://user-images.githubusercontent.com/14945613/140570776-e000149a-9909-4282-a77a-366d8eee8323.png">

**Comment by pkretzschmar** [comment]
I made a feature that makes the border of the input red if the value is not between the boundaries. Do you think that is enough?

**Comment by GriffGreen** [comment]
good enough :-D
