### ISSUE TITLE
It's too easy to lose your issue... make the cancel button a View your issue button, thats the right user flow

### ISSUE THREAD

**Issue by GriffGreen** [CommonsBuild/commons-config-frontend#178]
<img width="540" alt="Screen Shot 2021-11-05 at 2 56 05 PM" src="https://user-images.githubusercontent.com/14945613/140577571-23d3a6f3-90a7-4fd7-a557-1b6327cc9924.png">

**Comment by divine-comedian** [comment]
We should swap around the functionality a bit, we can close this modal by clicking anywhere outside of the modal. 

the button should say `VIEW PROPOSAL` and should link to the github issue

modify last sentence of text to say instead `To see your proposal in Github, click the button below.`
