### ISSUE TITLE
Add a few more lines to the Tao Voting table

### ISSUE THREAD

**Issue by GriffGreen** [CommonsBuild/commons-config-frontend#184]
The front end should have this info too

![Screen Shot 2021-11-07 at 12.43.59 PM.png](https://images.zenhubusercontent.com/597b3dc4f8b79f8376e1224b/e4aac385-31f2-4f61-9010-cb4069165a63)

**Comment by GriffGreen** [comment]
<img width="709" alt="Screen Shot 2021-11-10 at 11 00 15 PM" src="https://user-images.githubusercontent.com/14945613/141240708-fca84d79-5613-4a5d-8267-8fb99b7e9bb4.png">
Table is transposed... needs to be switched

**Comment by pkretzschmar** [comment]
Fixed on d0fb4c4e5eb7988ce83f2db5572e3c40c4c47f2e

**Comment by pkretzschmar** [comment]
Fixed on d0fb4c4e5eb7988ce83f2db5572e3c40c4c47f2e
