### ISSUE TITLE
Make the Transferable advanced param YES by default

### ISSUE THREAD

**Issue by GriffGreen** [CommonsBuild/commons-config-frontend#185]
now the default is blank which then turns to false!!! OH NO! Issue 1 is for a non transferable token!
<img width="537" alt="Screen Shot 2021-11-07 at 2 43 41 PM" src="https://user-images.githubusercontent.com/14945613/140661292-87b23bd3-56d7-4504-8898-fbfdbc1f3e4c.png">

**Comment by pkretzschmar** [comment]
solved at cf7c73f99904a3a2bb0cf911f3f429435e7cf9c8
