### ISSUE TITLE
Make everything for wxDai to use 2 decimals.

### ISSUE THREAD

**Issue by GriffGreen** [CommonsBuild/commons-config-frontend#196]
![Screen Shot 2021-11-09 at 9 56 01 AM](https://user-images.githubusercontent.com/14945613/140958585-e81e1ad3-0265-450d-b72a-e8d69bb49d80.png)
![Screen Shot 2021-11-09 at 9 55 57 AM](https://user-images.githubusercontent.com/14945613/140958590-8233c1f1-95fd-414d-ae23-3f7cba34159b.png)
![Screen Shot 2021-11-09 at 9 55 51 AM](https://user-images.githubusercontent.com/14945613/140958594-062a9791-92aa-43a4-8d31-4c95ed1cfbc2.png)
![Screen Shot 2021-11-09 at 9 55 46 AM](https://user-images.githubusercontent.com/14945613/140958597-e94ca8b5-3e43-4ae0-b730-d7b80a9c36aa.png)
![Screen Shot 2021-11-09 at 9 55 42 AM](https://user-images.githubusercontent.com/14945613/140958602-30936082-65c1-42ad-a918-a38402ac3f37.png)

**Comment by pkretzschmar** [comment]
Fixed at abca4f7bad7e080b02c7879fd777cb726e82daca
