### ISSUE TITLE
add calendar link to param parties in CCD navbar

### ISSUE THREAD

**Issue by divine-comedian** [CommonsBuild/commons-config-frontend#199]
let's put a button on the navbar of the dashboard to lead people to the google calendar  for param parties

button text along the lines of `Join a Param Party` or `Join a Params Session`

thoughts? @GriffGreen  @pkretzschmar

**Comment by divine-comedian** [comment]
## Like this?

![image](https://user-images.githubusercontent.com/67759413/141175488-90b91cbd-8a92-4227-8972-17977440ad19.png)

## or like this?

![image](https://user-images.githubusercontent.com/67759413/141175810-f0cd2e97-5d24-4122-99c8-5b563bb7e900.png)

@markoprljic  what do you think?

**Comment by markoprljic** [comment]
First option

**Comment by GriffGreen** [comment]
Love it!! Here is the link it should link to: https://calendar.google.com/calendar/u/0?cid=ZHRpbnQzYmE2NnY0cDJqN25uZWdlZnB2dmdAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ

**Comment by pkretzschmar** [comment]
Hey guys, I was looking at this feature and the main problem with the button was that we didn't have much space in lower resolution devices. So I came up with the idea that we could put some kind of footer with the message, like the image below.

![image](https://user-images.githubusercontent.com/43218565/141539243-63a36044-9f10-4cfd-84d4-d050b780eff1.png)

You guys can check the feature in the [preview here](https://commons-config-frontend-3uymqmemx-givethio.vercel.app/config/1). 

What are your thoughts @markoprljic, @GriffGreen, and @divine-comedian? I'm open to ideas on how to improve this!

**Comment by markoprljic** [comment]
Why don't we put the banner at the top over the main nav with the option to dismiss it (x icon or dismiss link)?

**Comment by GriffGreen** [comment]
Add music ! :-D j/k

**Comment by GriffGreen** [comment]
slow down or stop when you hoover over the calendar notfication
