### ISSUE TITLE
Add design graphics to intro and learn modules

### ISSUE THREAD

**Issue by divine-comedian** [CommonsBuild/commons-config-frontend#20]
the design assets that marko made are missing from the intro and learn modules. 

![image](https://user-images.githubusercontent.com/67759413/132355816-305d1166-1004-4fd2-89e7-fc78d284a2fd.png)

![image](https://user-images.githubusercontent.com/67759413/132356089-6d56dc0b-ef25-4b02-b4cd-036220ad0494.png)

**Comment by GriffGreen** [comment]
@pkretzschmar where would someone go to get this file? can they just pull it off the figma?
