### ISSUE TITLE
on CV module, the chart is saying "2 weeks" for ALL time periods

### ISSUE THREAD

**Issue by laurenluz** [CommonsBuild/commons-config-frontend#200]
Option 1: remove the time period entirely... you can see I have it set to "6 months"... so "2 weeks" is actually wrong.

Option 2: f it's not too much trouble, it would be *better* to have it say 7 days, 2 weeks, 1 month, 3 months, or 6 months... corresponding to what time period the user selected above.

but I think this should be fixed (at least option 1) asap because it's very confusing to the user. 

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/03fb79eb-c3c2-4614-9851-9d192f7d72b8)

**Comment by pkretzschmar** [comment]
Fixed at bc6c2ed08b84c3155a96a9080b313d0684995543

**Comment by GriffGreen** [comment]
This still hasnt been merged
