### ISSUE TITLE
ABC Step Simulator Improvements

### ISSUE THREAD

**Issue by GriffGreen** [CommonsBuild/commons-config-frontend#201]
Now that we have had some param parties... i think we can give some feed back for improvements

- [x] Step is confusing.. better to call it a transaction... or "Tx" if there isn't much space... I see it in 4 places

<img width="106" alt="Screen Shot 2021-11-21 at 12 03 31 PM" src="https://user-images.githubusercontent.com/14945613/142773680-de357bad-f67a-4866-ac24-a789b4ab64f7.png">
<img width="115" alt="Screen Shot 2021-11-21 at 12 03 25 PM" src="https://user-images.githubusercontent.com/14945613/142773681-a1448803-f842-4e4f-a8dd-2e2a318a083b.png">
<img width="104" alt="Screen Shot 2021-11-21 at 12 03 20 PM" src="https://user-images.githubusercontent.com/14945613/142773684-bf04c729-30bc-4357-9257-8d3bdfa8f049.png">

- [x] Remove the buttons: Launch, 100k, 500k... etc and just always show the graph at launch
<img width="342" alt="Screen Shot 2021-11-21 at 12 02 49 PM" src="https://user-images.githubusercontent.com/14945613/142773643-925df38f-82f6-4d69-a93f-5cdb95cbf2e0.png">

- [x] Remove bullish bearish options

<img width="285" alt="Screen Shot 2021-11-21 at 12 05 52 PM" src="https://user-images.githubusercontent.com/14945613/142773739-39721462-cfe5-4c5e-9833-1027fd5ecf6e.png">

- [x] Reserve balance seems like a Parameter... Remove it and add the "Reserve" into the Table... This will need a tool tip, here is the tool tip text "The amount of wxDAI that the bonding curve holds as collateral for the tokens" 

- [x] The "HOW TO USE THE SIMULATOR" pop up just got a lot easier..
It is now this: 
<img width="504" alt="Screen Shot 2021-11-21 at 12 11 56 PM" src="https://user-images.githubusercontent.com/14945613/142773944-f5a91d59-c4f6-4b06-a676-c1e15cdc988a.png">

But it should change to this text, no need for bullets, just 2 paragraphs:

Use the ABC Transaction Simulator to see how your configuration reacts to transactions. Note that Step 0 is the initial buy the mints tokens for the Commons itself, and the next 3 steps are generated automatically.

Click the "Add a Transaction" button, to place a buy or sell transaction on your ABC configuration. This will simulate a new transaction on your ABC. Take note that you can use large transactions to explore the full range of the ABC

- [x] At the end it should look like this:

Except it should still have the Learn More link and the text should say

SIMULATE BUY OR SELL TRANSACTIONS
Add more transaction to experience your ABC config

- [x] Add arrows for buys and sells

<img width="308" alt="Screen Shot 2021-11-21 at 1 23 19 PM" src="https://user-images.githubusercontent.com/14945613/142776071-2262eeb5-01ac-41f2-92b0-c28f599bd192.png">

**Comment by GriffGreen** [comment]
PR TO ADD THE RESERVE TO THE TABLE

**Comment by PabloCGL** [comment]
This one:
https://github.com/CommonsBuild/commons-config-backend/pull/70

**Comment by divine-comedian** [comment]
here's the proposed UI additions to the ABC table - 

![](https://cdn.discordapp.com/attachments/810180622634844204/903146540250574878/Image_2021-10-28_at_7.01.13_am.jpg)
