### ISSUE TITLE
When adjusting the opening price or the commons tribute, automatically reset the ABC module table and graph to Launch and Step 0

### ISSUE THREAD

**Issue by GriffGreen** [CommonsBuild/commons-config-frontend#202]
there seems to be a lot of confusion when people are playing around with the ABC especially when the reserve from a previous setting is left hanging.. then it seems like the table is giving bad data... this would be fixed by reseting to show the step 0 at launch ay time someone changes the opening price or commons tribute

They start here

<img width="962" alt="Screen Shot 2021-11-10 at 11 53 05 PM" src="https://user-images.githubusercontent.com/14945613/141245220-613185af-3ccb-4245-9f90-a8b1cccd1bc4.png">

Then they change the Commons Tribute... and then get confused when the opening price doesnt match the "current price" in step 1... because the reserve balance doesn't change

<img width="1052" alt="Screen Shot 2021-11-10 at 11 35 00 PM" src="https://user-images.githubusercontent.com/14945613/141243336-259c7fe2-72b2-410a-9661-09acc43c1e0a.png">

**Comment by pkretzschmar** [comment]
Fixed at 6e74296f95bff21c4556d665ccd0cbfc7ba62be6
