### ISSUE TITLE
Upon submitting, make the data for the ABC be the bullish setting not bearish

### ISSUE THREAD

**Issue by GriffGreen** [CommonsBuild/commons-config-frontend#204]
![Screen Shot 2021-11-12 at 10.31.12 AM.png](https://images.zenhubusercontent.com/597b3dc4f8b79f8376e1224b/64fa7843-4882-49cc-b317-b54a88346167)

In the github issue, we want all the data to be the same so it's easy to compare all the proposals... but in this one it's showing the bearish data

https://github.com/CommonsBuild/commons-config-proposals/issues/39

I think we just need to change the settings on submit to show the bullish scenario at launch (on step 0)

**Comment by pkretzschmar** [comment]
Fix at ece93cb84d1048ccbe923b408993c080229153ed
