### ISSUE TITLE
[Intro pages] On Firefox, the "learn more" popups get cut.

### ISSUE THREAD

**Issue by PabloCGL** [CommonsBuild/commons-config-frontend#65]
All 4 appear on a weird place and can't be read till the end, and the scroll bar doesn't move the popup:

![Issue_learnmodule](https://user-images.githubusercontent.com/50929773/136613795-cc34f2bb-ec3f-4d81-9033-b61ee042093b.png)

**Comment by divine-comedian** [comment]
I can confirm I have this same issue on Brave! 

Also there pop-ups would be cool if they close when you click anywhere outside of them, instead of exclusively when you need to click `OK` to close
