### ISSUE TITLE
Low pri - font size on token freeze & token thaw page is bigger in the first paragraph, small in the rest

### ISSUE THREAD

**Issue by laurenluz** [CommonsBuild/commons-config-frontend#90]
Should be consistent, no? :thinking: @divine-comedian 

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/a1fa2f4e-0742-4ace-bdf9-278836d33aef)

**Comment by laurenluz** [comment]
it's actually like this on all the learn module pages... is this on purpose?

**Comment by divine-comedian** [comment]
should be fixed with commit https://github.com/CommonsBuild/commons-config-frontend/commit/f6f0b8a6947e3fedb1747c87777a56d8b1857fbb
